name: Integración a DockerHub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      
      # proe
      - name: Checkout Code
        uses: actions/checkout@v4

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso 3: Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t examenproyectosistemas .

      # Paso 4: Etiquetar la imagen con el nombre de usuario de Docker Hub y un tag
      - name: Tag Docker Image
        run: |
          docker tag examenproyectosistemas ${{ secrets.DOCKERHUB_USERNAME }}/examenproyectosistemas:latest

      # Paso 5: Publicar la imagen en Docker Hub
      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/examenproyectosistemas:latest
